/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wishlist;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author leeca
 */
public class WishListGUI extends javax.swing.JFrame {
    
    WishList wishList;
    DefaultListModel listModel;
    File file;
    
    
    /**
     * Creates new form WishListGUI
     */
    public WishListGUI() {
        initComponents();
        this.setLocationRelativeTo(null); //position centre
         
        wishList = WishList.getInstance(); //singleton - get instance
        listModel = new DefaultListModel();
        
        try {
            wishList.readFile(); 
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(WishListGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.loadGifts();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        idLBL = new javax.swing.JLabel();
        descLBL = new javax.swing.JLabel();
        priceLBL = new javax.swing.JLabel();
        urlLBL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        descTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        urlTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        cheapBTN = new javax.swing.JButton();
        cmbGift = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGift = new javax.swing.JList<>();
        deleteBTN = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLBL.setText("ID:");

        descLBL.setText("DESC:");

        priceLBL.setText("PRICE:");

        urlLBL.setText("URL:");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        addBTN.setText("ADD:");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("SEARCH:");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        cheapBTN.setText("CHEAPEST:");
        cheapBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheapBTNActionPerformed(evt);
            }
        });

        cmbGift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BoardGame", "CraftSupplies", "Clothing" }));
        cmbGift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGiftActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstGift);

        deleteBTN.setText("DELETE:");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(idLBL)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(descLBL)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTF)
                                    .addComponent(descTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(urlLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbGift, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cheapBTN)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLBL)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLBL)
                            .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBTN)
                            .addComponent(searchBTN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cheapBTN)
                            .addComponent(deleteBTN))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlLBL)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        int number = Integer.parseInt(this.idTF.getText());
        String description = this.descTF.getText();
        int price = Integer.parseInt(this.priceTF.getText());
        String url = this.urlTF.getText();
        
        Gift gift = null;
        
        if(cmbGift.getSelectedItem().equals("BoardGame"))
        {
            String bgName = JOptionPane.showInputDialog("Please Enter Board Game Name : ");
            String bgPublisher = JOptionPane.showInputDialog("Please Enter Publishers Name : ");
            gift = new BoardGame(number, description, price, url, bgName, bgPublisher);
        }
        
        else if(cmbGift.getSelectedItem().equals("CraftSupplies")) 
        {
            String csName = JOptionPane.showInputDialog("Please Enter Craft Supply Type/Name : ");
            String csPublisher = JOptionPane.showInputDialog("Please Enter Publishers Name : ");
            gift = new CraftSupplies(number, description, price, url, csName, csPublisher);
        }
        
        else if(cmbGift.getSelectedItem().equals("Clothing"))
        {
            String type = JOptionPane.showInputDialog("Please Enter Clothing Type : ");
            String size = JOptionPane.showInputDialog("Please Enter Clothing Size : ");
            String color = JOptionPane.showInputDialog("Please Enter Clothing Color : ");
            gift = new Clothing(number, description, price, url, type, size, color);
        }
        
        wishList.addGift(gift);
        loadGifts(); //adds gifts to listModel
        
        try {
            wishList.saveFile();
        } catch (IOException ex) {
            System.out.println("IO Exception - line 219");
        }
    }//GEN-LAST:event_addBTNActionPerformed
    
    private void lstValueChanged()
    {
        if(!listModel.isEmpty()) 
            
            /* 
            when selected aspects will change to match the things in list
            */
        {
            int index = lstGift.getSelectedIndex();
            Gift gift = wishList.getGift().get(index);
            
            //setting text 
            this.idTF.setText(Integer.toString(gift.getNumber()));
            this.descTF.setText(gift.getDescription());
            this.priceTF.setText(Integer.toString(gift.getPrice()));
            this.urlTF.setText(gift.getUrl());
            
            //type casting in combo box.
            if(gift instanceof BoardGame)
            {
                cmbGift.setSelectedItem("BoardGame");
            }
            
            else if(gift instanceof CraftSupplies)
            {
                cmbGift.setSelectedItem("CraftSupplies");
            }
            
            else if(gift instanceof Clothing)
            {
                cmbGift.setSelectedItem("Clothing");
            }
            
        }
        
    }
    
    
    private void loadGifts()
    
    {
        listModel.clear();
        
        for(int i = 0; i<wishList.getGift().size(); i++)
        
        {
            Gift gift = wishList.getGift().get(i); //add each gift
            
            listModel.addElement(gift);
        }
        lstGift.setModel(listModel); //setting the model
    }
    
    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        //moot null
    }//GEN-LAST:event_idTFActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog("Please Enter Gift Number : "));
        
        int index = wishList.searchGift(id);
        
        if(index!=-1) //iterate as long as valid
        {
            this.lstGift.setSelectedIndex(index);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "NotFound");
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void cheapBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheapBTNActionPerformed
        // TODO add your handling code here:
   
            JOptionPane.showMessageDialog(null, "Cheapest is : "+wishList.findCheapest());
    
    
    }//GEN-LAST:event_cheapBTNActionPerformed

    private void cmbGiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGiftActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
       
        int index = lstGift.getSelectedIndex(); 
        //index is what you select in lstModel.
        wishList.deleteGift(index);
        
        loadGifts(); //re iterates the display
        
        try {
            wishList.saveFile();
        } catch (IOException ex) {
            Logger.getLogger(WishListGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WishListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton cheapBTN;
    private javax.swing.JComboBox<String> cmbGift;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel descLBL;
    private javax.swing.JTextField descTF;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTF;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstGift;
    private javax.swing.JLabel priceLBL;
    private javax.swing.JTextField priceTF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel urlLBL;
    private javax.swing.JTextField urlTF;
    // End of variables declaration//GEN-END:variables
}
